package com.tomaytotomato.aurora.services;

import com.tomaytotomato.aurora.config.AuroraProperties;
import com.tomaytotomato.aurora.domain.Package;
import com.tomaytotomato.aurora.domain.Role;
import com.tomaytotomato.aurora.domain.SsoBlock;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.mockito.Mockito;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Phase D iter-7 (D6) — {@link CaddySnippetService} render + reconcile.
 *
 * <p>Two halves:
 *
 * <ul>
 *   <li>{@code render()} pure-function tests — inject on
 *       {@code sso.protect: true}, pass-through when false, preserve
 *       source structure + indentation, banner comment stamped.</li>
 *   <li>End-to-end {@code reconcile()} tests via {@link TempDir} +
 *       mocked {@link PackagesService} — writes to
 *       {@code data/caddy/snippets/}, prunes stale, atomic-writes so
 *       Caddy's {@code --watch} never observes a torn file.</li>
 * </ul>
 */
class CaddySnippetServiceTests {

  @TempDir Path repoRoot;
  private PackagesService packages;
  private CaddySnippetService svc;

  private static final String NOTES_SRC = String.join("\n",
      "# aurora.local / packages/notes / caddy.snippet",
      "",
      "http://notes.{$DOMAIN} {",
      "\treverse_proxy silverbullet:3000",
      "}",
      "https://notes.{$DOMAIN} {",
      "\ttls internal",
      "\treverse_proxy silverbullet:3000",
      "}",
      ""
  );

  @BeforeEach
  void setUp() {
    packages = Mockito.mock(PackagesService.class);
    AuroraProperties props = new AuroraProperties(
        repoRoot.toString(), "/proc",
        List.of(),
        new AuroraProperties.Docker("unix:///dev/null")
    );
    svc = new CaddySnippetService(packages, props);
  }

  // ─── render() pure function ───────────────────────────────────────────

  @Test
  void render_injects_import_authelia_after_every_vhost_header_when_protected() {
    SsoBlock sso = new SsoBlock(true, Role.USER, false, java.util.List.of());
    String out = CaddySnippetService.render(NOTES_SRC, "notes", sso);

    // Both http:// and https:// vhosts get the import line.
    long injections = out.lines().filter(l -> l.trim().equals("import authelia")).count();
    assertThat(injections).isEqualTo(2);

    // Injection lands INSIDE the block, right after the header line.
    String[] lines = out.split("\\R");
    for (int i = 0; i < lines.length; i++) {
      if (lines[i].contains("http://notes.{$DOMAIN} {")) {
        assertThat(lines[i + 1].trim()).isEqualTo("import authelia");
      }
      if (lines[i].contains("https://notes.{$DOMAIN} {")) {
        assertThat(lines[i + 1].trim()).isEqualTo("import authelia");
      }
    }
  }

  @Test
  void render_passes_through_when_sso_disabled() {
    String out = CaddySnippetService.render(NOTES_SRC, "notes", SsoBlock.DISABLED);
    // The banner comment is prepended even for non-protected packages
    // so an operator peeking at the rendered file always sees where it
    // came from — but there's no `import authelia` anywhere.
    assertThat(out).doesNotContain("import authelia");
    assertThat(out).contains("regenerated by Aurora");
    // Every original vhost line survives verbatim.
    assertThat(out).contains("http://notes.{$DOMAIN} {");
    assertThat(out).contains("reverse_proxy silverbullet:3000");
  }

  @Test
  void render_banner_records_sso_block_details_for_protected_packages() {
    SsoBlock sso = new SsoBlock(true, Role.ADMIN, true, java.util.List.of());
    String out = CaddySnippetService.render(NOTES_SRC, "notes", sso);
    assertThat(out).contains("# regenerated by Aurora");
    assertThat(out).contains("# source: packages/notes/caddy.snippet");
    // Banner records the manifest sso: block verbatim so a debug
    // session doesn't have to cross-reference two files.
    assertThat(out).contains("min_role=admin");
    assertThat(out).contains("trusted_headers=true");
  }

  @Test
  void render_ignores_commented_out_vhost_lines() {
    String src = String.join("\n",
        "# http://ghost.{$DOMAIN} { reverse_proxy nowhere:80 }",
        "http://real.{$DOMAIN} {",
        "\treverse_proxy real:80",
        "}",
        ""
    );
    String out = CaddySnippetService.render(src, "x", new SsoBlock(true, Role.USER, false, java.util.List.of()));
    long injections = out.lines().filter(l -> l.trim().equals("import authelia")).count();
    // Only the real (non-commented) vhost header receives the injection.
    assertThat(injections).isEqualTo(1);
  }

  @Test
  void render_preserves_indent_style() {
    // Caddy tolerates any indent but consistent formatting reads
    // better in a debug session — the injected line matches the
    // surrounding block's leading whitespace shape.
    String src = "http://x.{$DOMAIN} {\n\treverse_proxy x:80\n}\n";
    String out = CaddySnippetService.render(src, "x", new SsoBlock(true, Role.USER, false, java.util.List.of()));
    // Because the header line uses a leading empty indent, the
    // injection uses a single tab (matches the source's inner indent).
    assertThat(out).contains("\timport authelia");
  }

  @Test
  void render_does_not_grow_by_a_trailing_newline_on_every_pass() {
    // If a future edit accidentally appends "\n" without trimming, a
    // 60-second drift loop would grow the file by one blank line per
    // tick — Caddy watcher would flap-reload forever.
    SsoBlock sso = new SsoBlock(true, Role.USER, false, java.util.List.of());
    String pass1 = CaddySnippetService.render(NOTES_SRC, "notes", sso);
    String pass2 = CaddySnippetService.render(pass1, "notes", sso);
    // pass2 will differ (banner appears twice) but its LENGTH shouldn't
    // grow unboundedly. Assert the growth is bounded to the banner
    // shape (~200 bytes), not the whole file.
    int growth = pass2.length() - pass1.length();
    assertThat(growth).isBetween(0, 400);
  }

  // ─── reconcile() end-to-end ───────────────────────────────────────────

  @Test
  void reconcile_writes_snippet_only_for_enabled_packages() throws IOException {
    seedPackageSource("notes", NOTES_SRC);
    seedPackageSource("media", "http://sonarr.{$DOMAIN} { reverse_proxy sonarr:8989 }\n");

    Mockito.when(packages.list()).thenReturn(List.of(
        pkg("notes", true,  new SsoBlock(true, Role.USER, false, java.util.List.of())),
        pkg("media", false, SsoBlock.DISABLED)      // disabled → skipped
    ));

    Set<String> written = svc.reconcile();
    assertThat(written).containsExactly("notes.caddy");
    assertThat(svc.snippetDir().resolve("notes.caddy")).exists();
    assertThat(svc.snippetDir().resolve("media.caddy")).doesNotExist();
  }

  @Test
  void reconcile_output_includes_import_authelia_when_protected() throws IOException {
    seedPackageSource("notes", NOTES_SRC);
    Mockito.when(packages.list()).thenReturn(List.of(
        pkg("notes", true, new SsoBlock(true, Role.USER, false, java.util.List.of()))
    ));

    svc.reconcile();

    String body = Files.readString(svc.snippetDir().resolve("notes.caddy"),
        StandardCharsets.UTF_8);
    assertThat(body).contains("import authelia");
    assertThat(body).contains("regenerated by Aurora");
  }

  @Test
  void reconcile_prunes_stale_snippets_on_disable() throws IOException {
    seedPackageSource("notes", NOTES_SRC);

    // First pass: notes enabled.
    Mockito.when(packages.list()).thenReturn(List.of(
        pkg("notes", true, new SsoBlock(true, Role.USER, false, java.util.List.of()))
    ));
    svc.reconcile();
    assertThat(svc.snippetDir().resolve("notes.caddy")).exists();

    // Second pass: notes disabled — snippet must go.
    Mockito.when(packages.list()).thenReturn(List.of(
        pkg("notes", false, SsoBlock.DISABLED)
    ));
    svc.reconcile();
    assertThat(svc.snippetDir().resolve("notes.caddy")).doesNotExist();
  }

  @Test
  void reconcile_prunes_stray_files_from_previous_installs() throws IOException {
    // Sit an old snippet in the output dir that no package claims.
    Files.createDirectories(svc.snippetDir());
    Files.writeString(svc.snippetDir().resolve("removed-package.caddy"), "# stale\n");

    Mockito.when(packages.list()).thenReturn(List.of());
    svc.reconcile();
    assertThat(svc.snippetDir().resolve("removed-package.caddy")).doesNotExist();
  }

  @Test
  void reconcile_skips_packages_without_a_caddy_snippet_file() throws IOException {
    // core has a manifest but ships no caddy.snippet — expected shape
    // for infrastructure-only packages (storage, privacy, etc.).
    Mockito.when(packages.list()).thenReturn(List.of(
        pkg("core", true, SsoBlock.DISABLED)
    ));
    Set<String> written = svc.reconcile();
    assertThat(written).isEmpty();
  }

  @Test
  void reconcile_is_idempotent_bytes_identical() throws IOException {
    seedPackageSource("notes", NOTES_SRC);
    Mockito.when(packages.list()).thenReturn(List.of(
        pkg("notes", true, new SsoBlock(true, Role.USER, false, java.util.List.of()))
    ));
    svc.reconcile();
    String first = Files.readString(svc.snippetDir().resolve("notes.caddy"),
        StandardCharsets.UTF_8);

    svc.reconcile();
    String second = Files.readString(svc.snippetDir().resolve("notes.caddy"),
        StandardCharsets.UTF_8);

    // Byte-for-byte identical — Caddy's --watch would otherwise
    // flap-reload every 60 seconds when the drift guard fires.
    assertThat(second).isEqualTo(first);
  }

  @Test
  void reconcile_updates_lastReconcileAt_and_clears_lastError() throws IOException {
    Mockito.when(packages.list()).thenReturn(List.of());
    assertThat(svc.lastReconcileAt()).isNull();
    svc.reconcile();
    assertThat(svc.lastReconcileAt()).isNotNull();
    assertThat(svc.lastError()).isNull();
  }

  // ─── helpers ──────────────────────────────────────────────────────────

  private Package pkg(String name, boolean enabled, SsoBlock sso) {
    return new Package(name, name, "d", "cat", List.of(), List.of(),
        Map.of(), List.of(), Map.of(), List.of(), null, enabled, false, sso);
  }

  private void seedPackageSource(String pkg, String snippetBody) throws IOException {
    Path dir = repoRoot.resolve("packages").resolve(pkg);
    Files.createDirectories(dir);
    Files.writeString(dir.resolve("caddy.snippet"), snippetBody, StandardCharsets.UTF_8);
  }
}
