---
- name: Ensure unattended-upgrades installed
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Deploy 20auto-upgrades
  ansible.builtin.template:
    src: 20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Deploy 50unattended-upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Ensure unattended-upgrades enabled
  ansible.builtin.systemd:
    name: unattended-upgrades
    enabled: true
    state: started
