---
# home.local / homepage / widgets.yaml
# https://gethomepage.dev/widgets/

- greeting:
    text_size: 4xl
    text: home.local

- datetime:
    text_size: xl
    format:
      dateStyle: full
      timeStyle: short
      hourCycle: h23

- resources:
    label: host
    cpu: true
    memory: true
    cputemp: true
    disk: /host
    uptime: true
    units: metric

- search:
    provider: duckduckgo
    focus: false
    target: _blank
