#!/usr/bin/env bash
# aurora.local / scripts/pin.sh
#
# Pin every service image referenced by packages/*/compose.yml to a
# specific registry digest. Rationale: docker compose pull silently
# advances "latest" (or any moving tag) so `./scripts/update.sh` can
# apply large changes without review. Pinning by digest makes updates
# an explicit git commit.
#
# Modes:
#   --check    (default) report current pins vs live registry digests
#   --refresh           re-resolve every image tag against the registry
#                       and rewrite pins.env
#   --apply             rewrite each compose.yml image line to use the
#                       pinned digest (with a header note). Requires a
#                       previous --refresh.
#
# Outputs one file per package: packages/<pkg>/pins.env with lines
#   IMAGE_<SVC>=repo/name@sha256:...
#
# Notes:
#   * Uses `docker buildx imagetools inspect` when available (handles
#     multi-arch); falls back to `docker manifest inspect`.
#   * A missing pins.env is treated as "everything drifted".

set -euo pipefail

# shellcheck source=lib/ops.sh
. "$(dirname "$0")/lib/ops.sh"

require_cmd docker

MODE=check
for a in "$@"; do
  case "$a" in
    --check)   MODE=check ;;
    --refresh) MODE=refresh ;;
    --apply)   MODE=apply ;;
    -h|--help) sed -n '2,25p' "$0"; exit 0 ;;
    *)         die "unknown arg: $a" ;;
  esac
done

# Resolve a `repo:tag` reference to `repo@sha256:...`.
resolve_digest() {
  local ref="$1" digest=""
  if docker buildx version >/dev/null 2>&1; then
    digest=$(docker buildx imagetools inspect "$ref" 2>/dev/null \
      | awk '/^Digest:/ {print $2; exit}') || true
  fi
  if [[ -z "$digest" ]]; then
    digest=$(docker manifest inspect "$ref" 2>/dev/null \
      | awk -F\" '/"digest"/ {print $4; exit}') || true
  fi
  if [[ -z "$digest" ]]; then
    return 1
  fi
  local repo="${ref%%:*}"
  # If ref had no tag, ${ref%%:*} still ok since no colon.
  printf '%s@%s\n' "$repo" "$digest"
}

# Extract "service<TAB>image" pairs from a compose.yml. Naive but fine
# for the shapes we emit (top-level `services:` then `<name>:` then
# `image: <ref>` within that block).
extract_services() {
  local f="$1"
  awk '
    /^services:/ { in_services=1; next }
    in_services && /^[a-zA-Z_]/ { in_services=0 }
    in_services && /^[[:space:]]{2}[a-zA-Z0-9_-]+:[[:space:]]*$/ {
      svc=$0; sub(/^[[:space:]]+/,"",svc); sub(/:.*/,"",svc); next
    }
    in_services && svc && /^[[:space:]]+image:[[:space:]]*/ {
      img=$0; sub(/^[[:space:]]+image:[[:space:]]*/,"",img)
      gsub(/["'\'']/,"",img)
      sub(/[[:space:]]*#.*/,"",img)
      # Skip already-digested refs (contain @sha256)
      if (img !~ /@sha256:/) print svc "\t" img
    }
  ' "$f"
}

svc_var() {  # foo-bar -> FOO_BAR
  printf '%s' "$1" | tr '[:lower:]-' '[:upper:]_'
}

drift_report=()
declare -A newpins   # pkg|svc -> pinned ref
declare -A oldpins   # pkg|svc -> previous ref

# Load existing pins.
for pkg in $(list_all_packages); do
  # shellcheck disable=SC2153
  p="$REPO/packages/$pkg/pins.env"
  [[ -f "$p" ]] || continue
  while IFS='=' read -r k v; do
    [[ "$k" =~ ^IMAGE_ ]] || continue
    svc="${k#IMAGE_}"
    oldpins["$pkg|$svc"]="$v"
  done < <(grep -E '^IMAGE_' "$p" || true)
done

# For each package, walk services.
for pkg in $(list_all_packages); do
  f="$REPO/packages/$pkg/compose.yml"
  log "package: $pkg"
  while IFS=$'\t' read -r svc img; do
    [[ -z "$svc" ]] && continue
    svc_u=$(svc_var "$svc")
    key="$pkg|$svc_u"
    case "$MODE" in
      refresh|apply)
        if pinned=$(resolve_digest "$img"); then
          dim "  $svc: $img -> $pinned"
          newpins["$key"]="$pinned"
        else
          warn "  $svc: could not resolve $img (skipped)"
        fi
        ;;
      check)
        if pinned=$(resolve_digest "$img"); then
          old="${oldpins[$key]:-}"
          if [[ -z "$old" ]]; then
            drift_report+=("$pkg/$svc: NEW ($pinned)")
          elif [[ "$old" == "$pinned" ]]; then
            ok "  $svc: up-to-date"
          else
            drift_report+=("$pkg/$svc: DRIFT")
            drift_report+=("    old: $old")
            drift_report+=("    new: $pinned")
          fi
        else
          warn "  $svc: cannot query $img"
        fi
        ;;
    esac
  done < <(extract_services "$f")
done

# Write pins.env files (refresh / apply).
if [[ "$MODE" == "refresh" || "$MODE" == "apply" ]]; then
  declare -A byPkg
  for key in "${!newpins[@]}"; do
    pkg="${key%%|*}"; svc="${key##*|}"
    byPkg[$pkg]+="IMAGE_${svc}=${newpins[$key]}"$'\n'
  done
  for pkg in "${!byPkg[@]}"; do
    out="$REPO/packages/$pkg/pins.env"
    {
      printf '# aurora.local / packages/%s/pins.env\n' "$pkg"
      printf '# Regenerated by scripts/pin.sh --refresh at %s\n' "$(date -Iseconds)"
      # shellcheck disable=SC2016
      printf '%s\n' '# Consumed by compose via ${IMAGE_<SVC>} substitution when --apply'
      printf '# has been run against compose.yml.\n\n'
      printf '%s' "${byPkg[$pkg]}"
    } > "$out"
    ok "wrote $out"
  done
fi

# Apply: rewrite compose.yml image: lines to use ${IMAGE_<SVC>} refs.
if [[ "$MODE" == "apply" ]]; then
  for pkg in "${!byPkg[@]}"; do
    f="$REPO/packages/$pkg/compose.yml"
    [[ -f "$f" ]] || continue
    tmp="$(mktemp)"
    awk '
      BEGIN { svc="" }
      /^services:/ { in_s=1; print; next }
      in_s && /^[a-zA-Z_]/ { in_s=0 }
      in_s && /^[[:space:]]{2}[a-zA-Z0-9_-]+:[[:space:]]*$/ {
        svc=$0; sub(/^[[:space:]]+/,"",svc); sub(/:.*/,"",svc)
        print; next
      }
      in_s && svc && /^[[:space:]]+image:[[:space:]]*/ && $0 !~ /\$\{IMAGE_/ {
        indent=$0; sub(/[^[:space:]].*/,"",indent)
        up=svc; gsub(/-/,"_",up); up=toupper(up)
        print indent "image: ${IMAGE_" up ":-" gensub(/^[[:space:]]+image:[[:space:]]*/,"","g",$0) "}"
        next
      }
      { print }
    ' "$f" > "$tmp"
    if ! diff -q "$f" "$tmp" >/dev/null; then
      mv "$tmp" "$f"
      ok "rewrote $f"
    else
      rm -f "$tmp"
    fi
  done
  warn "run './scripts/up.sh' to pick up the pinned images"
fi

# Print drift summary.
if [[ "$MODE" == "check" ]]; then
  echo
  if (( ${#drift_report[@]} == 0 )); then
    ok "no drift; all packages pinned to current registry digests"
  else
    warn "drift detected:"
    printf '  %s\n' "${drift_report[@]}"
    echo
    dim "run './scripts/pin.sh --refresh' to update pins.env"
    dim "then './scripts/pin.sh --apply' to rewrite compose.yml image: lines"
    exit 2
  fi
fi
