package com.tomaytotomato.aurora.services;

import com.tomaytotomato.aurora.config.AuroraProperties;
import com.tomaytotomato.aurora.domain.Package;
import com.tomaytotomato.aurora.domain.SsoBlock;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.event.ApplicationReadyEvent;
import org.springframework.context.event.EventListener;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.nio.file.StandardOpenOption;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.atomic.AtomicReference;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Phase D iter-7 (D6) — render {@code data/caddy/snippets/*.caddy}
 * from every enabled package's {@code caddy.snippet}, injecting
 * {@code import authelia} inside every vhost block when the manifest
 * declares {@code sso.protect: true}.
 *
 * <p><b>Why a service, not the shell renderer?</b> The bash
 * {@code scripts/lib/render.sh} runs at {@code scripts/up.sh} time,
 * before Aurora is up, and does a raw copy of the snippet — good
 * enough for bootstrap. Once Aurora is running it takes ownership of
 * the file so package enable/disable, sso-block edits, and role
 * rewrites reflect in Caddy without another {@code up.sh}. Caddy
 * runs with {@code --watch} (see packages/core/compose.yml) so the
 * reload happens within ~2s of the atomic rename. Same pattern as
 * AutheliaService owning {@code users_database.yml} and
 * IdentitySecretsService owning {@code packages/identity/.env}.
 *
 * <p><b>What the injection looks like.</b>
 *
 * <pre>
 * # Input packages/notes/caddy.snippet (checked into git):
 *
 * http://notes.{$DOMAIN} {
 *     reverse_proxy silverbullet:3000
 * }
 * https://notes.{$DOMAIN} {
 *     tls internal
 *     reverse_proxy silverbullet:3000
 * }
 *
 * # Output data/caddy/snippets/notes.caddy (regenerated on every reconcile):
 *
 * # regenerated by Aurora CaddySnippetService — do not hand-edit.
 * # sso: protect=true min_role=user trusted_headers=false
 *
 * http://notes.{$DOMAIN} {
 *     import authelia
 *     reverse_proxy silverbullet:3000
 * }
 * https://notes.{$DOMAIN} {
 *     tls internal
 *     import authelia
 *     reverse_proxy silverbullet:3000
 * }
 * </pre>
 *
 * <p><b>What Aurora does NOT emit.</b> Per-vhost {@code min_role}
 * gating and trusted-header rewrites live in Authelia's
 * {@code access_control.rules} + Caddy's {@code copy_headers} directive
 * — both handled by the reusable {@code (authelia)} snippet in
 * {@code packages/identity/caddy.snippet}. D6 only decides whether
 * the vhost gets the {@code import} line at all; {@code min_role} +
 * {@code trusted_headers} land in D7 and D12.
 *
 * <p><b>Prune policy.</b> Stale snippets (package no longer enabled,
 * or package deleted) get removed from {@code data/caddy/snippets/}
 * on every reconcile. Caddy's own {@code import} directive tolerates
 * missing files with a warn — pruning keeps the surface tidy.
 *
 * <p><b>Reconcile cadence.</b> {@link ApplicationReadyEvent} +
 * {@code fixedDelay = 60_000} drift guard. No user-change hook (a
 * users edit doesn't affect snippet contents; a package enable/disable
 * would — currently there's no first-class event for that, and the
 * 60s drift is fine for a homelab where package flips are rare and
 * `scripts/up.sh` also runs `render_caddy_snippets` inline).
 */
@Service
public class CaddySnippetService {

  private static final Logger log = LoggerFactory.getLogger(CaddySnippetService.class);

  /** Matches the vhost header line {@code http(s)://…{$DOMAIN} {}. */
  private static final Pattern VHOST_HEADER = Pattern.compile(
      "^(\\s*)(https?://[A-Za-z0-9][A-Za-z0-9.\\-]*\\{\\$DOMAIN}(?:[^{]*)?)\\{\\s*$"
  );

  private final PackagesService packages;
  private final AuroraProperties props;

  private final AtomicReference<Instant> lastReconcileAt = new AtomicReference<>(null);
  private final AtomicReference<String> lastError = new AtomicReference<>(null);

  public CaddySnippetService(PackagesService packages, AuroraProperties props) {
    this.packages = packages;
    this.props = props;
  }

  // ─── lifecycle ────────────────────────────────────────────────────────

  @EventListener(ApplicationReadyEvent.class)
  public void onReady() {
    try {
      reconcile();
    } catch (Exception e) {
      // Same fail-closed pattern as AutheliaService — a snippet write
      // failure must never crash the dashboard at boot.
      lastError.set(e.getClass().getSimpleName() + ": " + e.getMessage());
      log.warn("caddy snippet reconcile failed at startup: {}", e.getMessage());
    }
  }

  @Scheduled(fixedDelay = 60_000L, initialDelay = 60_000L)
  public void scheduledReconcile() {
    try {
      reconcile();
    } catch (Exception e) {
      lastError.set(e.getClass().getSimpleName() + ": " + e.getMessage());
      log.warn("caddy snippet scheduled reconcile threw: {}", e.getMessage());
    }
  }

  // ─── public API ───────────────────────────────────────────────────────

  /**
   * Idempotent full render. Returns the set of snippet filenames now
   * present in {@code data/caddy/snippets/} so callers can assert.
   */
  public synchronized Set<String> reconcile() throws IOException {
    Path outDir = snippetDir();
    Files.createDirectories(outDir);

    Set<String> want = new LinkedHashSet<>();
    List<Package> pkgs = packages.list();
    for (Package pkg : pkgs) {
      if (!pkg.enabled()) continue;
      Path srcSnippet = packageSnippetPath(pkg.name());
      if (!Files.isRegularFile(srcSnippet)) continue;

      String src = Files.readString(srcSnippet, StandardCharsets.UTF_8);
      String rendered = render(src, pkg.name(), pkg.sso());
      atomicWrite(outDir.resolve(pkg.name() + ".caddy"), rendered);
      want.add(pkg.name() + ".caddy");
    }

    // Prune stale snippets whose package flipped off or vanished.
    pruneStale(outDir, want);

    lastReconcileAt.set(Instant.now());
    lastError.set(null);
    log.debug("caddy snippet reconcile complete — {} snippet(s) present", want.size());
    return want;
  }

  public Instant lastReconcileAt() { return lastReconcileAt.get(); }
  public String lastError() { return lastError.get(); }
  public Path snippetDir() {
    return Path.of(props.repoPath(), "data", "caddy", "snippets");
  }
  Path packageSnippetPath(String pkg) {
    return Path.of(props.repoPath(), "packages", pkg, "caddy.snippet");
  }

  // ─── rendering ────────────────────────────────────────────────────────

  /**
   * Package-private for tests. Injects {@code import authelia} inside
   * every vhost header block when {@code sso.protect} is true; passes
   * the snippet through verbatim otherwise. Adds a banner comment so
   * an operator reading the rendered file understands why it looks
   * different from the source.
   */
  static String render(String source, String pkgName, SsoBlock sso) {
    var out = new StringBuilder();
    out.append("# regenerated by Aurora CaddySnippetService — do not hand-edit.\n");
    out.append("# source: packages/").append(pkgName).append("/caddy.snippet\n");
    if (sso != null && sso.protect()) {
      out.append("# sso: protect=true min_role=").append(sso.minRole().wireName())
         .append(" trusted_headers=").append(sso.trustedHeaders()).append('\n');
    }
    out.append('\n');

    boolean inject = sso != null && sso.protect();
    for (String line : source.split("\\R", -1)) {
      out.append(line).append('\n');
      if (inject) {
        Matcher m = VHOST_HEADER.matcher(line);
        if (m.matches()) {
          // Preserve the leading indent so the imported directive
          // aligns with the rest of the block. Caddy tolerates any
          // whitespace but consistent formatting reads better in a
          // debug session.
          String indent = m.group(1);
          out.append(indent).append('\t').append("import authelia\n");
        }
      }
    }
    // split with -1 keeps a trailing empty entry when the source ends in a
    // newline; strip a single trailing extra newline so we don't grow the
    // file on every reconcile.
    String rendered = out.toString();
    if (rendered.endsWith("\n\n")) rendered = rendered.substring(0, rendered.length() - 1);
    return rendered;
  }

  // ─── file ops ─────────────────────────────────────────────────────────

  static void atomicWrite(Path target, String contents) throws IOException {
    Files.createDirectories(target.getParent());
    Path tmp = Files.createTempFile(target.getParent(),
        target.getFileName().toString() + ".", ".tmp");
    try (var w = Files.newBufferedWriter(tmp, StandardCharsets.UTF_8,
        StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING)) {
      w.write(contents);
    }
    try {
      Files.move(tmp, target,
          StandardCopyOption.REPLACE_EXISTING,
          StandardCopyOption.ATOMIC_MOVE);
    } catch (IOException e) {
      try { Files.deleteIfExists(tmp); } catch (IOException ignore) { /* best-effort */ }
      throw e;
    }
  }

  private void pruneStale(Path outDir, Set<String> keep) throws IOException {
    if (!Files.isDirectory(outDir)) return;
    List<Path> stale = new ArrayList<>();
    try (DirectoryStream<Path> s = Files.newDirectoryStream(outDir, "*.caddy")) {
      for (Path p : s) {
        if (!keep.contains(p.getFileName().toString())) stale.add(p);
      }
    }
    for (Path p : stale) {
      try {
        Files.delete(p);
        log.info("pruned stale caddy snippet: {}", p.getFileName());
      } catch (IOException e) {
        // Non-fatal — a snippet we can't delete is just noise Caddy
        // ignores on the next reload; log and carry on.
        log.warn("failed to prune stale caddy snippet {}: {}", p, e.getMessage());
      }
    }
  }
}
