package com.tomaytotomato.aurora.services;

import com.tomaytotomato.aurora.domain.OpenVpnClient;
import com.tomaytotomato.aurora.domain.OpenVpnConfig;
import com.tomaytotomato.aurora.persistence.OpenVpnClientRepo;
import com.tomaytotomato.aurora.persistence.OpenVpnConfigRepo;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

/**
 * The secondary, off-by-default OpenVPN server — see {@code
 * VPN_PAGE_DESIGN.md} §3.4 "Advanced tab" for why this domain is
 * deliberately smaller than {@link VpnService}'s WireGuard side: no
 * keypair, no QR flow, no split/full-tunnel choice, no live traffic
 * counters. A client's {@code .ovpn} text here is a static placeholder
 * body rather than something generated from a real OpenVPN CA, because
 * standing up a CA is out of scope for tonight and there is no {@code
 * packages/vpn} compose bundle yet to hand it to (see VPN_PAGE_DESIGN.md
 * §7 — the compose bundle itself is explicitly out of scope for the
 * page design too).
 */
@Service
public class OpenVpnService {

  private static final Logger log = LoggerFactory.getLogger(OpenVpnService.class);

  private final OpenVpnConfigRepo configRepo;
  private final OpenVpnClientRepo clientRepo;

  public OpenVpnService(OpenVpnConfigRepo configRepo, OpenVpnClientRepo clientRepo) {
    this.configRepo = configRepo;
    this.clientRepo = clientRepo;
  }

  public OpenVpnConfig getConfig() {
    return configRepo.find();
  }

  public OpenVpnConfig updateConfig(boolean enabled, int port, String protocol) {
    configRepo.update(enabled, port, protocol);
    log.info("vpn: openvpn config updated enabled={} port={} protocol={}", enabled, port, protocol);
    return configRepo.find();
  }

  public List<OpenVpnClient> listClients() {
    return clientRepo.findAll();
  }

  public record NewClient(OpenVpnClient client, String confText) {}

  public NewClient addClient(String name) {
    OpenVpnClient client = new OpenVpnClient(
        UUID.randomUUID().toString(), name, Instant.now().toString(), null);
    clientRepo.insert(client);
    log.info("vpn: openvpn client added id={} name={}", client.id(), client.name());
    String confText = buildConfText(client);
    return new NewClient(client, confText);
  }

  public void deleteClient(String id) {
    if (clientRepo.deleteById(id) == 0) {
      throw new java.util.NoSuchElementException("no such openvpn client: " + id);
    }
    log.info("vpn: openvpn client removed id={}", id);
  }

  /**
   * A structurally valid but non-functional placeholder — no real CA
   * exists yet to sign this client's cert. Deliberately unlike the
   * WireGuard peer flow (which yields a genuinely working key), because
   * generating a private key we would then need to embed here without a
   * real CA to countersign it would be worse than saying plainly that
   * the OpenVPN side is config/bookkeeping only in this iteration.
   */
  private static String buildConfText(OpenVpnClient client) {
    return """
        # OpenVPN client profile for '%s'
        # Generated by Aurora — placeholder only. Aurora does not run a
        # real OpenVPN CA/server yet, so this file has no working
        # <cert>/<key> block. Fill those in against your own OpenVPN
        # server, or use the WireGuard tab, which is fully wired.
        client
        dev tun
        proto udp
        """.formatted(client.name());
  }
}
